version: 2
builds:
  - main: cmd/keywordminer/main.go
    binary: keywordminer
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags: 
      - -s -w
    # クロスコンパイル時はCGO_ENABLEDはデフォルトでは有効にならない。なので有効にしたが
    # linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99
    # がでるので今回は無効化する
    env:
      - CGO_ENABLED=0
# archives.replacements - Deprecation notices - GoReleaser https://goreleaser.com/deprecations/?h=replacements#archivesreplacements
archives:
  - id: main
    format: zip  # アーカイブ形式を明示的に指定
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README*
      - LICENSE*
# プロジェクトの完全なビルドを生成したいが、何も検証したくないし、どこかにアップロードもしたくないという場合があります。
# GoReleaser は --snapshot フラグとスナップショット カスタマイズ セクションでこれをサポートします。
# snapshots - Snapshots - GoReleaser https://goreleaser.com/customization/snapshots/?h=snapshot#snapshots
# goreleaser build --snapshot --clean
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
