name: release

on:
  push:
    tags: #vX.X.Xというタグのときにリリースする
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write # これがないとリリースを作成できない
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
      -
        name: Run Tests
        run: go test -v ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub Actionsが自動的に生成するトークン
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
